[book]
title = "あまりにも超大量の連結リストで学ぶRust"
author = "Alexis Beingessner"
description = "Learning Rust With Entirely Too Many Linked Lists"
language = "ja"

[build]
build-dir = "book"
create-missing = false

[output.html.search]
limit-results = 30
